# These are supported funding model platforms

github: [SmartProBono]
patreon: smartprobono
open_collective: smart-pro-bono
ko_fi: smartprobono
liberapay: smartprobono
custom: ['https://www.smartprobono.org/donate', 'https://paypal.me/smartprobono']

# You can add the following platforms if needed in the future:
# community_bridge: 
# issuehunt: 
# otechie: 
# tidelift: 