import React from 'react';
import { Paper, Typography, Box, Divider, Grid } from '@mui/material';

function PrintableContract({ content, metadata }) {
  return (
    <Paper
      sx={{
        p: 4,
        m: 2,
        maxWidth: '800px',
        margin: 'auto',
        '@media print': {
          boxShadow: 'none',
          margin: 0,
        },
      }}
    >
      <Box className="contract-header" sx={{ mb: 4, textAlign: 'center' }}>
        <Typography variant="h4" gutterBottom>
          {metadata?.title || 'Legal Document'}
        </Typography>
        <Typography variant="subtitle1" color="text.secondary">
          Date: {metadata?.date || new Date().toLocaleDateString()}
        </Typography>
      </Box>

      <Divider sx={{ mb: 4 }} />

      <Box className="contract-content" sx={{ mb: 4 }}>
        <Typography variant="body1" paragraph>
          {content}
        </Typography>
      </Box>

      <Divider sx={{ mb: 4 }} />

      <Box className="contract-signatures" sx={{ mt: 4 }}>
        <Grid container spacing={4}>
          <Grid item xs={6}>
            <Typography variant="body2" gutterBottom>
              Party 1:
            </Typography>
            <Box sx={{ mt: 4, borderTop: '1px solid #000', width: '80%' }}>
              <Typography variant="caption">Signature & Date</Typography>
            </Box>
          </Grid>
          <Grid item xs={6}>
            <Typography variant="body2" gutterBottom>
              Party 2:
            </Typography>
            <Box sx={{ mt: 4, borderTop: '1px solid #000', width: '80%' }}>
              <Typography variant="caption">Signature & Date</Typography>
            </Box>
          </Grid>
        </Grid>
      </Box>

      <Box className="contract-footer" sx={{ mt: 6, textAlign: 'center' }}>
        <Typography variant="caption" color="text.secondary">
          Generated by SmartProBono Legal Assistant
        </Typography>
      </Box>
    </Paper>
  );
}

export default PrintableContract;
