name: 🐛 Bug Report
description: Report a bug to help us improve SmartProBono
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more information you provide, the better we can help you.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check these boxes before submitting your issue
      options:
        - label: I have checked that this issue has not already been reported
          required: true
        - label: I have tested this in the latest version
          required: true

  - type: dropdown
    attributes:
      label: Component
      description: Which part of SmartProBono is affected?
      options:
        - AI Legal Assistant
        - Document Generation
        - Legal Rights Information
        - Multi-language Support
        - Case Progress Tracking
        - Identity Verification
        - User Interface
        - Backend API
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is
      placeholder: |
        Example: When I try to generate a document, the system shows an error message...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: |
        Example: The document should be generated and downloaded as a PDF...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please complete the following information
      value: |
        - OS: [e.g. Windows, macOS, Linux]
        - Browser: [e.g. Chrome, Safari, Firefox]
        - Version: [e.g. 22]
        - Device: [e.g. Desktop, iPhone, Android]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, logs)
      placeholder: |
        You can attach images or log files by clicking this area to highlight it and then dragging files in.

  - type: dropdown
    attributes:
      label: Impact
      description: How critical is this bug to your use of SmartProBono?
      options:
        - Critical - Completely blocks my work
        - High - Major feature is broken
        - Medium - Inconvenient but workable
        - Low - Minor annoyance
    validations:
      required: true 