name: 💡 Feature Request
description: Suggest an idea for SmartProBono
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check these boxes before submitting your feature request
      options:
        - label: I have checked that this feature has not already been requested
          required: true
        - label: I have considered the impact on all user types (clients, lawyers, administrators)
          required: true

  - type: dropdown
    attributes:
      label: Feature Category
      description: What area of SmartProBono would this feature enhance?
      options:
        - AI Legal Assistant
        - Document Generation
        - Legal Rights Information
        - Multi-language Support
        - Case Progress Tracking
        - Identity Verification
        - User Interface
        - Backend API
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        Example: I'm always frustrated when trying to [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        Example: It would be helpful if the system could [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: |
        Example: Another way to solve this would be [...]

  - type: textarea
    attributes:
      label: User Impact
      description: How would this feature benefit SmartProBono users?
      placeholder: |
        Example: This would help users by [...]
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Needed for core functionality
        - High - Would significantly improve usability
        - Medium - Nice to have
        - Low - Just an idea
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here
      placeholder: |
        You can attach images or mockups by clicking this area to highlight it and then dragging files in. 